## USB port
port: /dev/imu


##### Calibration ####
### accelerometer
accel_x_min: -255.0
accel_x_max: 255.37
accel_y_min: -267.58
accel_y_max: 271.0
accel_z_min: -276.25
accel_z_max: 269.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [271.146, -647.024, -871.448]
magn_ellipsoid_transform: [[0.900135, -2.88781e-05, -0.00664110], [-2.88781e-05, 0.915566, 0.0186368], [-0.00664110, 0.0186368, 0.995444]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 0.025
gyro_average_offset_y: 0.0
gyro_average_offset_z: -0.017
